{
  "labels": {
    "backend": "local",
    "platform": "linux/arm64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "secrets": [
        "attic_key"
      ]
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
